### ISSUE TITLE
weird proof?

### ISSUE THREAD

**Issue by themathqueen** [glams-lean-2024/formal-2024#23]
```lean
lemma weird {α : Type*} : Nonempty α → α := by
  intro h
  rcases h with ⟨x⟩ 
  exact x
``` 

This one gives an error

_Originally posted by @SimoneCastellan in https://github.com/glams-lean-2024/formal-2024/pull/21#discussion_r1504003344_

**Comment by SimoneCastellan** [comment]
`The error message recursor 'Exists.casesOn' can only eliminate into Prop means that this only works when the current goal is another proposition:`
